CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS __JOBS_TABLE__ ();
ALTER TABLE __JOBS_TABLE__ ADD COLUMN IF NOT EXISTS id uuid PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE __JOBS_TABLE__ ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT NOW();
ALTER TABLE __JOBS_TABLE__ ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT NOW();
ALTER TABLE __JOBS_TABLE__ ADD COLUMN IF NOT EXISTS channel text NOT NULL;
ALTER TABLE __JOBS_TABLE__ ADD COLUMN IF NOT EXISTS priority integer NOT NULL DEFAULT 0;
ALTER TABLE __JOBS_TABLE__ ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'WAITING';
ALTER TABLE __JOBS_TABLE__ ADD COLUMN IF NOT EXISTS start_after timestamp with time zone NOT NULL DEFAULT NOW();
ALTER TABLE __JOBS_TABLE__ ADD COLUMN IF NOT EXISTS max_retries integer NOT NULL DEFAULT 0;
ALTER TABLE __JOBS_TABLE__ ADD COLUMN IF NOT EXISTS retry_delay interval;
ALTER TABLE __JOBS_TABLE__ ADD COLUMN IF NOT EXISTS args jsonb;

CREATE TABLE IF NOT EXISTS __RUNS_TABLE__ ();
ALTER TABLE __RUNS_TABLE__ ADD COLUMN IF NOT EXISTS id uuid PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE __RUNS_TABLE__ ADD COLUMN IF NOT EXISTS job_id uuid NOT NULL;
ALTER TABLE __RUNS_TABLE__ ADD COLUMN IF NOT EXISTS started_at timestamp with time zone NOT NULL;
ALTER TABLE __RUNS_TABLE__ ADD COLUMN IF NOT EXISTS finished_at timestamp with time zone NOT NULL;
ALTER TABLE __RUNS_TABLE__ ADD COLUMN IF NOT EXISTS status text NOT NULL;
ALTER TABLE __RUNS_TABLE__ ADD COLUMN IF NOT EXISTS result jsonb;
ALTER TABLE __RUNS_TABLE__ ADD FOREIGN KEY (job_id) REFERENCES __JOBS_TABLE__ (id);
